int main() {
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    printf("non siamo comunisti");
    return 1;
}

